"""Create calendar_events & calendar_reminder_jobs

Revision ID: 14ece55ca4f6
Revises: 
Create Date: 2025-07-16 12:50:47.931860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ece55ca4f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'COMPLETED', 'CANCELLED', name='event_status'), nullable=False),
    sa.Column('google_status', sa.String(length=50), nullable=True),
    sa.Column('google_updated', sa.DateTime(), nullable=True),
    sa.Column('google_etag', sa.String(length=100), nullable=True),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('attendees_count', sa.Integer(), nullable=False),
    sa.Column('has_reminders', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('scheduler_job_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_calendar_events_calendar_id'), 'calendar_events', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_end_time'), 'calendar_events', ['end_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_scheduler_job_id'), 'calendar_events', ['scheduler_job_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_table('calendar_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('sync_token', sa.String(length=1000), nullable=True),
    sa.Column('next_sync_token', sa.String(length=1000), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('channel_expiration', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id')
    )
    op.create_table('planning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE', name='plan_status'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_sessions_date'), 'planning_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_planning_sessions_user_id'), 'planning_sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('default_reminder_minutes_before', sa.Integer(), nullable=False),
    sa.Column('enable_task_start_reminders', sa.Boolean(), nullable=False),
    sa.Column('enable_task_due_reminders', sa.Boolean(), nullable=False),
    sa.Column('enable_planning_reminders', sa.Boolean(), nullable=False),
    sa.Column('preferred_planning_time', sa.String(length=5), nullable=True),
    sa.Column('auto_schedule_tasks', sa.Boolean(), nullable=False),
    sa.Column('default_task_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('calendar_reminder_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_calendar_reminder_jobs_event_id'), 'calendar_reminder_jobs', ['event_id'], unique=False)
    op.create_index(op.f('ix_calendar_reminder_jobs_start_time'), 'calendar_reminder_jobs', ['start_time'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='task_priority'), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=100), nullable=True),
    sa.Column('slack_thread_ts', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['planning_session_id'], ['planning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('reminder_type', sa.Enum('TASK_START', 'TASK_DUE', 'PLANNING_SESSION', 'CUSTOM', name='reminder_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheduler_job_id', sa.String(length=100), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_calendar_reminder_jobs_start_time'), table_name='calendar_reminder_jobs')
    op.drop_index(op.f('ix_calendar_reminder_jobs_event_id'), table_name='calendar_reminder_jobs')
    op.drop_table('calendar_reminder_jobs')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_planning_sessions_user_id'), table_name='planning_sessions')
    op.drop_index(op.f('ix_planning_sessions_date'), table_name='planning_sessions')
    op.drop_table('planning_sessions')
    op.drop_table('calendar_sync')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_scheduler_job_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_end_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_calendar_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
