"""add slack_scheduled_message_id and haunt_attempt to planning_sessions

Revision ID: f886a323ad4e
Revises: a3daabe987df
Create Date: 2025-07-16 15:25:04.237633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f886a323ad4e'
down_revision: Union[str, Sequence[str], None] = 'a3daabe987df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_sessions', sa.Column('scheduler_job_id', sa.String(length=100), nullable=True))
    op.add_column('planning_sessions', sa.Column('slack_scheduled_message_id', sa.String(length=100), nullable=True))
    op.add_column('planning_sessions', sa.Column('haunt_attempt', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_planning_sessions_scheduler_job_id'), 'planning_sessions', ['scheduler_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planning_sessions_scheduler_job_id'), table_name='planning_sessions')
    op.drop_column('planning_sessions', 'haunt_attempt')
    op.drop_column('planning_sessions', 'slack_scheduled_message_id')
    op.drop_column('planning_sessions', 'scheduler_job_id')
    # ### end Alembic commands ###
